
import { DocState, UserRole } from './types';

// Maps the business rules to UI properties
export const STATE_CONFIG: Record<DocState, { label: string; color: string; progress: number }> = {
  [DocState.NOT_STARTED]: { label: 'No Iniciado', color: 'bg-slate-100 text-slate-400 border border-slate-200', progress: 0 },
  [DocState.INITIATED]: { label: 'Iniciado (0.0)', color: 'bg-gray-100 text-gray-800', progress: 10 },
  [DocState.IN_PROCESS]: { label: 'En Proceso (0.n)', color: 'bg-blue-100 text-blue-800', progress: 30 },
  [DocState.INTERNAL_REVIEW]: { label: 'Revisión Interna (V0.n)', color: 'bg-yellow-100 text-yellow-800', progress: 60 },
  [DocState.SENT_TO_REFERENT]: { label: 'Enviado a Referente (V1.n)', color: 'bg-purple-100 text-purple-800', progress: 80 },
  [DocState.REFERENT_REVIEW]: { label: 'Revisión Interna Referente (V1.n.i)', color: 'bg-indigo-100 text-indigo-800', progress: 80 },
  [DocState.SENT_TO_CONTROL]: { label: 'Enviado a Control (V1.nAR)', color: 'bg-orange-100 text-orange-800', progress: 90 },
  [DocState.CONTROL_REVIEW]: { label: 'Revisión Interna Control (V1.n.iAR)', color: 'bg-pink-100 text-pink-800', progress: 90 },
  [DocState.APPROVED]: { label: 'Aprobado Final (V1.nACG)', color: 'bg-green-100 text-green-800', progress: 100 },
  [DocState.REJECTED]: { label: 'Rechazado', color: 'bg-red-100 text-red-800', progress: 0 },
};

// Mock Users for Simulation
export const MOCK_USERS = [
  {
    id: 'admin',
    email: 'admin@empresa.com',
    name: 'Administrador General',
    nickname: 'admin',
    role: UserRole.ADMIN,
    avatar: 'https://ui-avatars.com/api/?name=Admin&background=333&color=fff',
    organization: 'Dirección',
    password: 'admin'
  }
];

export const NAME_TO_ID_MAP: Record<string, string> = {};
export const INITIAL_DATA_LOAD: string[][] = [];
export const DOCUMENT_STATUS_LOAD: string[][] = [];

export const REQUIRED_DOCS_MATRIX = [
    ["HPC", "Admisión Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Admisión Toma de Muestras", 1, 1, 1, 1],
    ["HPC", "Anatomía Patológica", 1, 1, 1, 1],
    ["HPC", "Atención Consultas Ambulatorias", 1, 1, 1, 1],
    ["HPC", "Atención de Urgencias", 0, 1, 0, 1],
    ["HPC", "Atención Procedimientos", 1, 1, 1, 1],
    ["HPC", "Capacitación Funcionario", 1, 1, 1, 1],
    ["HPC", "Cirugía Menor Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Contratación", 1, 1, 1, 1],
    ["HPC", "Desinfección de Alto Nivel DAN", 1, 1, 1, 1],
    ["HPC", "Diálisis", 0, 1, 0, 1],
    ["HPC", "Esterilización", 1, 1, 1, 1],
    ["HPC", "Farmacia Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Gestión de Agenda", 1, 1, 1, 1],
    ["HPC", "Gestión de Citas", 1, 1, 1, 1],
    ["HPC", "Gestión de Contratos", 1, 1, 1, 1],
    ["HPC", "Gestión de Fallecidos", 0, 1, 0, 1],
    ["HPC", "Gestión de IC", 1, 1, 1, 1],
    ["HPC", "Listas de Espera GES", 1, 1, 1, 1],
    ["HPC", "Listas de Espera No GES", 1, 1, 1, 1],
    ["HPC", "Gestión de Pabellones", 0, 1, 0, 1],
    ["HPC", "Gestión Prequirúrgico", 0, 1, 0, 1],
    ["HPC", "Hospital de Día MQ", 0, 1, 0, 1],
    ["HPC", "Hospital de Día SM", 1, 1, 1, 1],
    ["HPC", "Hospitalización Domiciliaria", 1, 1, 1, 1],
    ["HPC", "Imagenología", 1, 1, 1, 1],
    ["HPC", "Laboratorio", 0, 1, 0, 1],
    ["HPC", "Mantenimiento de Equipos", 1, 1, 1, 1],
    ["HPC", "Mantenimiento Infraestructura", 1, 1, 1, 1],
    ["HPC", "Procedimientos Endoscópicos", 1, 1, 1, 1],
    ["HPC", "Programación de Fármacos", 1, 1, 1, 1],
    ["HPC", "Programación PCA", 1, 1, 1, 1],
    ["HPC", "Recaudación Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Reclutamiento y Selección Funcionarios", 1, 1, 1, 1],
    ["HPC", "TACO", 1, 1, 1, 1],
    ["HPC", "Toma de Muestras Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Trato Laboral", 1, 1, 1, 1],
    ["HPC", "Gestión de Transfusión Sanguínea", 0, 1, 0, 1],
    ["HPC", "Asistencia", 1, 1, 1, 1],
    ["HPC", "Atención de Rehabilitación Oral", 1, 1, 1, 1],
    ["HPC", "Atención de Radiología Dental", 1, 1, 1, 1],
    ["HPC", "Atención de Periodoncia", 1, 1, 1, 1],
    ["HPC", "Atención de Odontopediatría", 1, 1, 1, 1],
    ["HPC", "Atención de Endodoncia", 1, 1, 1, 1],
    ["HPC", "Atención de Ortodoncia", 1, 1, 1, 1],
    ["HPC", "Roperia", 0, 1, 0, 1],
    ["HPC", "Atención de Cirugía Maxilofacial", 1, 1, 1, 1],
    ["HPC", "Beneficios Funcionarios", 1, 1, 1, 1],
    ["HPC", "Gestión de Bodegas", 1, 1, 1, 1],
    ["HPC", "Gestión de Compras", 1, 1, 1, 1],
    ["HPC", "Liquidación de Pago", 1, 1, 1, 1],
    ["HPC", "Servicios de Vestidores", 0, 1, 0, 1],
    ["HPC", "Gestión de OIRS", 1, 1, 1, 1],
    ["HPC", "Relaciones Públicas", 1, 1, 1, 1],
    ["HPC", "Gestión de Mesa de Ayuda", 1, 1, 1, 1],
    ["HPC", "Gestión de Proyectos", 1, 1, 1, 1],
    ["HPC", "Administración de Activos", 1, 1, 1, 1],
    ["HPC", "Gestión de Ingresos y Gastos", 1, 1, 1, 1],
    ["HPC", "Gestión de Tesorería", 1, 1, 1, 1],
    ["HPC", "Monitoreo y auditoría de cuentas contables", 1, 1, 1, 1],
    ["HPC", "Elaboración de Reportes", 1, 1, 1, 1],
    ["HPC", "Gestión de Donantes", 0, 1, 0, 1],
    ["HPC", "Atención de TTM", 1, 1, 1, 1],
    ["HPC", "Licencias Médicas", 1, 1, 1, 1],
    ["HPC", "Traslado de Pacientes", 0, 1, 0, 1],
    ["HPC", "Remuneración Funcionarios", 1, 1, 1, 1],
    ["HPC", "Gestión de Hemocomponentes", 0, 1, 0, 1],
    ["HPC", "Kinesiología Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Hospitalización", 0, 1, 0, 1],
    ["HPC", "Quimioterapia", 0, 1, 0, 1],
    ["HSR", "Adquisición de Servicios", 0, 0, 0, 1],
    ["HSR", "Esterilización", 0, 0, 0, 1],
    ["HSR", "Farmacia Ambulatoria", 0, 0, 0, 1],
    ["HSR", "Gestión de Agenda", 0, 0, 0, 1],
    ["HSR", "Gestión de Citas", 0, 0, 0, 1],
    ["HSR", "Gestión de Contratos", 0, 0, 0, 1],
    ["HSR", "Gestión de Fallecidos", 0, 0, 0, 1],
    ["HSR", "Gestión de IC", 0, 0, 0, 1],
    ["HSR", "Listas de Espera No GES", 0, 0, 0, 1],
    ["HSR", "Gestión de Pabellones", 0, 0, 0, 1],
    ["HSR", "Gestión Prequirúrgico", 0, 0, 0, 1],
    ["HSR", "Hospital de Día MQ", 0, 0, 0, 1],
    ["HSR", "Imagenología", 0, 0, 0, 1],
    ["HSR", "Laboratorio", 0, 0, 0, 1],
    ["HSR", "Oncología", 0, 0, 0, 1],
    ["HSR", "Toma de Muestras Ambulatoria", 0, 0, 0, 1],
    ["HSR", "Gestión de Transfusión Sanguínea", 0, 0, 0, 1],
    ["HSR", "Procesamiento de Biopsias", 0, 0, 0, 1],
    ["HSR", "Procesamiento de Citología PAP", 0, 0, 0, 1],
    ["HSR", "Oncología Adulto", 0, 0, 0, 1],
    ["HSR", "Oncología Ginecológica", 0, 0, 0, 1],
    ["HSR", "Oncología Infantil", 0, 0, 0, 1],
    ["HSR", "Procesamiento de Citología Misceláneas", 0, 0, 0, 1],
    ["HSR", "Gestión de Bodegas", 0, 0, 0, 1],
    ["HSR", "Gestión de Compras", 0, 0, 0, 1],
    ["HSR", "Liquidación de Pago", 0, 0, 0, 1],
    ["HSR", "Gestión de Donantes", 0, 0, 0, 1],
    ["HSR", "Gestión de Alimentación y Nutrición", 0, 0, 0, 1],
    ["HSR", "Gestión ANI Adulto en Atención cerrada", 0, 0, 0, 1],
    ["HSR", "Gestión ANI Adulto en Atención Ambulatoria", 0, 0, 0, 1],
    ["HSR", "Gestión ANI Adulto en Hospitalización Domiciliaria", 0, 0, 0, 1],
    ["HSR", "Hematología", 0, 0, 0, 1],
    ["HSR", "Uroanálisis", 0, 0, 0, 1],
    ["HSR", "Recepción de Laboratorio Clínico", 0, 0, 0, 1],
    ["HSR", "Gestión de Hemocomponentes", 0, 0, 0, 1],
    ["HSR", "Gestión de Camas", 0, 0, 0, 1],
    ["HSR", "Hospitalización", 0, 0, 0, 1],
    ["HSR", "Gestión de Material en Archivo", 0, 0, 0, 1]
] as [string, string, number, number, number, number][];
