

import { DocState, UserRole } from './types';

// Maps the business rules to UI properties
export const STATE_CONFIG: Record<DocState, { label: string; color: string; progress: number }> = {
  [DocState.INITIATED]: { label: 'Iniciado (0.0)', color: 'bg-gray-100 text-gray-800', progress: 10 },
  [DocState.IN_PROCESS]: { label: 'En Proceso (0.n)', color: 'bg-blue-100 text-blue-800', progress: 30 },
  [DocState.INTERNAL_REVIEW]: { label: 'Revisión Interna (v0.n)', color: 'bg-yellow-100 text-yellow-800', progress: 60 },
  [DocState.SENT_TO_REFERENT]: { label: 'Enviado a Referente (v1.n)', color: 'bg-purple-100 text-purple-800', progress: 80 },
  [DocState.REFERENT_REVIEW]: { label: 'Revisión Referente (v1.n.i)', color: 'bg-indigo-100 text-indigo-800', progress: 80 },
  [DocState.SENT_TO_CONTROL]: { label: 'Control de Gestión (v1.nAR)', color: 'bg-orange-100 text-orange-800', progress: 90 },
  [DocState.CONTROL_REVIEW]: { label: 'Revisión Control (v1.n.iAR)', color: 'bg-pink-100 text-pink-800', progress: 90 },
  [DocState.APPROVED]: { label: 'Aprobado Final (v1.nACG)', color: 'bg-green-100 text-green-800', progress: 100 },
  [DocState.REJECTED]: { label: 'Rechazado', color: 'bg-red-100 text-red-800', progress: 0 },
};

// Mock Users for Simulation
export const MOCK_USERS = [
  {
    id: 'admin',
    email: 'admin@empresa.com',
    name: 'Administrador General',
    nickname: 'admin',
    role: UserRole.ADMIN,
    avatar: 'https://ui-avatars.com/api/?name=Admin&background=333&color=fff',
    organization: 'Dirección',
    password: 'admin'
  },
  {
    id: 'u-pveloz',
    email: 'pveloz@empresa.com',
    name: 'Patricio Veloz',
    nickname: 'pveloz',
    role: UserRole.COORDINATOR,
    avatar: 'https://ui-avatars.com/api/?name=Patricio+Veloz&background=random',
    organization: 'Coordinación Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-arebolledo',
    email: 'arebolledo@empresa.com',
    name: 'Alejandra Rebolledo',
    nickname: 'arebolledo',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Alejandra+Rebolledo&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-aorellana',
    email: 'Andrea Orellana',
    name: 'Andrea Orellana',
    nickname: 'aorellana',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Andrea+Orellana&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-bsiebold',
    email: 'bsiebold@empresa.com',
    name: 'Barbara Siebold',
    nickname: 'bsiebold',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Barbara+Siebold&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-cvalenzuela',
    email: 'cvalenzuela@empresa.com',
    name: 'Carolina Valenzuela',
    nickname: 'cvalenzuela',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Carolina+Valenzuela&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-caraya',
    email: 'caraya@empresa.com',
    name: 'Christian Araya',
    nickname: 'caraya',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Christian+Araya&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-csalvo',
    email: 'csalvo@empresa.com',
    name: 'Christian Salvo',
    nickname: 'csalvo',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Christian+Salvo&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-jcalquin',
    email: 'jcalquin@empresa.com',
    name: 'Javiera Calquin',
    nickname: 'jcalquin',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Javiera+Calquin&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-mcofre',
    email: 'mcofre@empresa.com',
    name: 'Maximiliano Cofre',
    nickname: 'mcofre',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Maximiliano+Cofre&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  }
];

export const NAME_TO_ID_MAP: Record<string, string> = {
  'Christian Araya': 'u-caraya',
  'Christian Salvo': 'u-csalvo',
  'Carolina Valenzuela': 'u-cvalenzuela',
  'Maximiliano Cofre': 'u-mcofre',
  'Alejandra Rebolledo': 'u-arebolledo',
  'Javiera Calquin': 'u-jcalquin',
  'Andrea Orellana': 'u-aorellana',
  'Barbara Siebold': 'u-bsiebold',
  'Andrea': 'u-aorellana', // Alias for combined
  'Javiera': 'u-jcalquin'  // Alias for combined
};

// Defines the hierarchy and assignments
export const INITIAL_DATA_LOAD = [
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Abastecimiento", "Gestión de Bodegas", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Abastecimiento", "Gestión de Compras", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Abastecimiento", "Gestión de Contratos", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Abastecimiento", "Programación de Fármacos", "Christian Salvo"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Esterilización", "Desinfección de Alto Nivel DAN", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Esterilización", "Esterilización", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Finanzas", "Administración de Activos", "Carolina Valenzuela"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Finanzas", "Gestión de Ingresos y Gastos", "Carolina Valenzuela"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Finanzas", "Gestión de Tesorería", "Carolina Valenzuela"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Finanzas", "Liquidación de Pago", "Carolina Valenzuela"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Finanzas", "Monitoreo y auditoría de cuentas contables", "Carolina Valenzuela"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Finanzas", "Recaudación Ambulatoria", "Christian Salvo"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Asistencia", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Beneficios Funcionarios", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Capacitación Funcionario", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Contratación", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Licencias Médicas", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Reclutamiento y Selección Funcionarios", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Remuneración Funcionarios", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Trato Laboral", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Servicios Generales", "Gestión de Mesa de Ayuda", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Servicios Generales", "Mantenimiento de Equipos", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Servicios Generales", "Mantenimiento Infraestructura", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Servicios Generales", "Roperia", "Alejandra Rebolledo"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Servicios Generales", "Servicios de Vestidores", "Alejandra Rebolledo"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Servicios Generales", "Traslado de Pacientes", "Christian Araya"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Apoyo Atención Ambulatoria", "Admisión Ambulatoria", "Christian Salvo"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Apoyo Atención Ambulatoria", "Admisión Toma de Muestras", "Christian Salvo"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Apoyo Atención Ambulatoria", "Gestión de Agenda", "Javiera Calquin"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Apoyo Atención Ambulatoria", "Gestión de Citas", "Javiera Calquin"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Gestión de la Demanda", "Gestión de IC", "Javiera Calquin"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Gestión de la Demanda", "Listas de Espera GES", "Javiera Calquin"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Gestión de la Demanda", "Listas de Espera No GES", "Javiera Calquin"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "Gestión Prequirúrgico", "Andrea Orellana"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "Quimioterapia", "Andrea Orellana"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "TACO", "Andrea Orellana"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Procedimientos especiales", "Gestión de Fallecidos", "Javiera Calquin"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Anatomía Patológica", "Anatomía Patológica", "Javiera Calquin"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Farmacia", "Farmacia Ambulatoria", "Christian Salvo"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Imagenología", "Imagenología", "Javiera Calquin"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Laboratorio", "Toma de Muestras Ambulatoria", "Barbara Siebold"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Pabellón Quirúrgico", "Gestión de Pabellones", "Andrea Orellana"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Pabellón Quirúrgico", "Procedimientos Endoscópicos", "Andrea Orellana"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Procedimientos", "Atención Procedimientos", "Andrea Orellana"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Procedimientos", "Cirugía Menor Ambulatoria", "Andrea Orellana"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Procedimientos", "Diálisis", "Christian Araya"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Unidad de Medicina Transfusional", "Gestión de Transfusión Sanguínea", "Andrea Orellana"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Medicina Física y Rehabilitación", "Kinesiología Ambulatoria", "Carolina Valenzuela"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención Consultas Ambulatorias", "Andrea Orellana"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de Cirugía Maxilofacial", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de Endodoncia", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de Odontopediatría", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de Ortodoncia", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de Periodoncia", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de Radiología Dental", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de Rehabilitación Oral", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de TTM", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Hospitalizados", "Hospital de Día MQ", "Barbara Siebold"],
  ["HPC", "Principales", "Atención Hospitalizados", "Hospital de Día SM", "Barbara Siebold"],
  ["HPC", "Principales", "Atención Hospitalizados", "Hospitalización", "Barbara Siebold"],
  ["HPC", "Principales", "Atención Hospitalizados", "Hospitalización Domiciliaria", "Barbara Siebold"],
  ["HPC", "Principales", "Atención Urgencia", "Atención de Urgencias", "Barbara Siebold"],
  ["HPC", "Dirección", "Control de Gestión", "Elaboración de Reportes", "Carolina Valenzuela"],
  ["HPC", "Dirección", "Control de Gestión", "Programación PCA", "Andrea/Javiera"],
  ["HPC", "Dirección", "Gestión de Proyectos", "Gestión de Proyectos", "Christian Araya"],
  ["HPC", "Dirección", "Relacionamiento con la Comunidad", "Gestión de OIRS", "Alejandra Rebolledo"],
  ["HPC", "Dirección", "Relacionamiento con la Comunidad", "Relaciones Públicas", "Alejandra Rebolledo"],
  ["HSR", "Apoyo Administrativo Logístico e Industrial", "Abastecimiento", "Adquisición de Servicios", "Christian Araya"],
  ["HSR", "Apoyo Administrativo Logístico e Industrial", "Abastecimiento", "Gestión de Compras", "Christian Araya"],
  ["HSR", "Apoyo Administrativo Logístico e Industrial", "Abastecimiento", "Gestión de Contratos", "Christian Araya"],
  ["HSR", "Apoyo Administrativo Logístico e Industrial", "Esterilización", "Esterilización", "Christian Araya"],
  ["HSR", "Apoyo Administrativo Logístico e Industrial", "Finanzas", "Liquidación de Pago", "Carolina Valenzuela"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Apoyo Atención Ambulatoria", "Gestión de Agenda", "Javiera Calquin"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Apoyo Atención Ambulatoria", "Gestión de Citas", "Javiera Calquin"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Gestión de la Demanda", "Gestión de IC", "Javiera Calquin"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Gestión de la Demanda", "Listas de Espera No GES", "Javiera Calquin"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "Gestión Prequirúrgico", "Andrea Orellana"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "Oncología", "Barbara Siebold"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "Oncología Adulto", "Barbara Siebold"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "Oncología Ginecológica", "Barbara Siebold"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "Oncología Infantil", "Barbara Siebold"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Procedimientos especiales", "Gestión de Fallecidos", "Javiera Calquin"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Apoyo Atención Hospitalaria", "Gestión de Camas", "Barbara Siebold"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Anatomía Patológica", "Gestión de Material en Archivo", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Anatomía Patológica", "Procesamiento de Biopsias", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Anatomía Patológica", "Procesamiento de Citología Misceláneas", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Anatomía Patológica", "Procesamiento de Citología PAP", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Farmacia", "Farmacia Ambulatoria", "Christian Salvo"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Imagenología", "Imagenología", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Laboratorio", "Hematología", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Laboratorio", "Recepción de Laboratorio Clínico", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Laboratorio", "Toma de Muestras Ambulatoria", "Barbara Siebold"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Laboratorio", "Uroanálisis", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Nutrición", "Gestión ANI Adulto en Atención cerrada", "Alejandra Rebolledo"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Nutrición", "Gestión ANI Adulto en Hospitalización Domiciliaria", "Alejandra Rebolledo"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Nutrición", "Gestión de Alimentación y Nutrición", "Alejandra Rebolledo"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Pabellón Quirúrgico", "Gestión de Pabellones", "Andrea Orellana"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Unidad de Medicina Transfusional", "Gestión de Donantes", "Andrea Orellana"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Unidad de Medicina Transfusional", "Gestión de Hemocomponentes", "Andrea Orellana"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Unidad de Medicina Transfusional", "Gestión de Transfusión Sanguínea", "Andrea Orellana"],
  ["HSR", "Principales", "Atención Hospitalizados", "Hospital de Día MQ", "Barbara Siebold"],
  ["HSR", "Principales", "Atención Hospitalizados", "Hospitalización", "Barbara Siebold"]
];

// Defines the actual document status, version and type for seed
// EMPTY ARRAY for clean slate production/upload use
export const DOCUMENT_STATUS_LOAD = [
];

// Definition Matrix for Required Documents per Microprocess
// Format: [Project, Microprocess, AS IS(0/1), FCE(0/1), PM(0/1), TO BE(0/1)]
export const REQUIRED_DOCS_MATRIX = [
    // HPC
    ["HPC", "Admisión Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Admisión Toma de Muestras", 1, 1, 1, 1],
    ["HPC", "Anatomía Patológica", 1, 1, 1, 1],
    ["HPC", "Atención Consultas Ambulatorias", 1, 1, 1, 1],
    ["HPC", "Atención de Urgencias", 0, 1, 0, 1],
    ["HPC", "Atención Procedimientos", 1, 1, 1, 1],
    ["HPC", "Capacitación Funcionario", 1, 1, 1, 1],
    ["HPC", "Cirugía Menor Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Contratación", 1, 1, 1, 1],
    ["HPC", "Desinfección de Alto Nivel DAN", 1, 1, 1, 1],
    ["HPC", "Diálisis", 0, 1, 0, 1],
    ["HPC", "Esterilización", 1, 1, 1, 1],
    ["HPC", "Farmacia Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Gestión de Agenda", 1, 1, 1, 1],
    ["HPC", "Gestión de Citas", 1, 1, 1, 1],
    ["HPC", "Gestión de Contratos", 1, 1, 1, 1],
    ["HPC", "Gestión de Fallecidos", 0, 1, 0, 1],
    ["HPC", "Gestión de IC", 1, 1, 1, 1],
    ["HPC", "Listas de Espera GES", 1, 1, 1, 1],
    ["HPC", "Listas de Espera No GES", 1, 1, 1, 1],
    ["HPC", "Gestión de Pabellones", 0, 1, 0, 1],
    ["HPC", "Gestión Prequirúrgico", 0, 1, 0, 1],
    ["HPC", "Hospital de Día MQ", 0, 1, 0, 1],
    ["HPC", "Hospital de Día SM", 1, 1, 1, 1],
    ["HPC", "Hospitalización Domiciliaria", 1, 1, 1, 1],
    ["HPC", "Imagenología", 1, 1, 1, 1],
    ["HPC", "Laboratorio", 0, 1, 0, 1],
    ["HPC", "Mantenimiento de Equipos", 1, 1, 1, 1],
    ["HPC", "Mantenimiento Infraestructura", 1, 1, 1, 1],
    ["HPC", "Procedimientos Endoscópicos", 1, 1, 1, 1],
    ["HPC", "Programación de Fármacos", 1, 1, 1, 1],
    ["HPC", "Programación PCA", 1, 1, 1, 1],
    ["HPC", "Recaudación Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Reclutamiento y Selección Funcionarios", 1, 1, 1, 1],
    ["HPC", "TACO", 1, 1, 1, 1],
    ["HPC", "Toma de Muestras Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Trato Laboral", 1, 1, 1, 1],
    ["HPC", "Gestión de Transfusión Sanguínea", 0, 1, 0, 1],
    ["HPC", "Asistencia", 1, 1, 1, 1],
    ["HPC", "Atención de Rehabilitación Oral", 1, 1, 1, 1],
    ["HPC", "Atención de Radiología Dental", 1, 1, 1, 1],
    ["HPC", "Atención de Periodoncia", 1, 1, 1, 1],
    ["HPC", "Atención de Odontopediatría", 1, 1, 1, 1],
    ["HPC", "Atención de Endodoncia", 1, 1, 1, 1],
    ["HPC", "Atención de Ortodoncia", 1, 1, 1, 1],
    ["HPC", "Roperia", 0, 1, 0, 1],
    ["HPC", "Atención de Cirugía Maxilofacial", 1, 1, 1, 1],
    ["HPC", "Beneficios Funcionarios", 1, 1, 1, 1],
    ["HPC", "Gestión de Bodegas", 1, 1, 1, 1],
    ["HPC", "Gestión de Compras", 1, 1, 1, 1],
    ["HPC", "Liquidación de Pago", 1, 1, 1, 1],
    ["HPC", "Servicios de Vestidores", 0, 1, 0, 1],
    ["HPC", "Gestión de OIRS", 1, 1, 1, 1],
    ["HPC", "Relaciones Públicas", 1, 1, 1, 1],
    ["HPC", "Gestión de Mesa de Ayuda", 1, 1, 1, 1],
    ["HPC", "Gestión de Proyectos", 1, 1, 1, 1],
    ["HPC", "Administración de Activos", 1, 1, 1, 1],
    ["HPC", "Gestión de Ingresos y Gastos", 1, 1, 1, 1],
    ["HPC", "Gestión de Tesorería", 1, 1, 1, 1],
    ["HPC", "Monitoreo y auditoría de cuentas contables", 1, 1, 1, 1],
    ["HPC", "Elaboración de Reportes", 1, 1, 1, 1],
    ["HPC", "Gestión de Donantes", 0, 1, 0, 1],
    ["HPC", "Atención de TTM", 1, 1, 1, 1],
    ["HPC", "Licencias Médicas", 1, 1, 1, 1],
    ["HPC", "Traslado de Pacientes", 0, 1, 0, 1],
    ["HPC", "Remuneración Funcionarios", 1, 1, 1, 1],
    ["HPC", "Gestión de Hemocomponentes", 0, 1, 0, 1],
    ["HPC", "Kinesiología Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Hospitalización", 0, 1, 0, 1],
    ["HPC", "Quimioterapia", 0, 1, 0, 1],
    
    // HSR
    ["HSR", "Adquisición de Servicios", 0, 0, 0, 1],
    ["HSR", "Esterilización", 0, 0, 0, 1],
    ["HSR", "Farmacia Ambulatoria", 0, 0, 0, 1],
    ["HSR", "Gestión de Agenda", 0, 0, 0, 1],
    ["HSR", "Gestión de Citas", 0, 0, 0, 1],
    ["HSR", "Gestión de Contratos", 0, 0, 0, 1],
    ["HSR", "Gestión de Fallecidos", 0, 0, 0, 1],
    ["HSR", "Gestión de IC", 0, 0, 0, 1],
    ["HSR", "Listas de Espera No GES", 0, 0, 0, 1],
    ["HSR", "Gestión de Pabellones", 0, 0, 0, 1],
    ["HSR", "Gestión Prequirúrgico", 0, 0, 0, 1],
    ["HSR", "Hospital de Día MQ", 0, 0, 0, 1],
    ["HSR", "Imagenología", 0, 0, 0, 1],
    ["HSR", "Laboratorio", 0, 0, 0, 1],
    ["HSR", "Oncología", 0, 0, 0, 1],
    ["HSR", "Toma de Muestras Ambulatoria", 0, 0, 0, 1],
    ["HSR", "Gestión de Transfusión Sanguínea", 0, 0, 0, 1],
    ["HSR", "Procesamiento de Biopsias", 0, 0, 0, 1],
    ["HSR", "Procesamiento de Citología PAP", 0, 0, 0, 1],
    ["HSR", "Oncología Adulto", 0, 0, 0, 1],
    ["HSR", "Oncología Ginecológica", 0, 0, 0, 1],
    ["HSR", "Oncología Infantil", 0, 0, 0, 1],
    ["HSR", "Procesamiento de Citología Misceláneas", 0, 0, 0, 1],
    ["HSR", "Gestión de Bodegas", 0, 0, 0, 1],
    ["HSR", "Gestión de Compras", 0, 0, 0, 1],
    ["HSR", "Liquidación de Pago", 0, 0, 0, 1],
    ["HSR", "Gestión de Donantes", 0, 0, 0, 1],
    ["HSR", "Gestión de Alimentación y Nutrición", 0, 0, 0, 1],
    ["HSR", "Gestión ANI Adulto en Atención cerrada", 0, 0, 0, 1],
    ["HSR", "Gestión ANI Adulto en Atención Ambulatoria", 0, 0, 0, 1],
    ["HSR", "Gestión ANI Adulto en Hospitalización Domiciliaria", 0, 0, 0, 1],
    ["HSR", "Hematología", 0, 0, 0, 1],
    ["HSR", "Uroanálisis", 0, 0, 0, 1],
    ["HSR", "Recepción de Laboratorio Clínico", 0, 0, 0, 1],
    ["HSR", "Gestión de Hemocomponentes", 0, 0, 0, 1],
    ["HSR", "Gestión de Camas", 0, 0, 0, 1],
    ["HSR", "Hospitalización", 0, 0, 0, 1],
    ["HSR", "Gestión de Material en Archivo", 0, 0, 0, 1]
] as [string, string, number, number, number, number][];