
import { DocState, UserRole } from './types';

// Maps the business rules to UI properties
export const STATE_CONFIG: Record<DocState, { label: string; color: string; progress: number }> = {
  [DocState.INITIATED]: { label: 'Iniciado (0.0)', color: 'bg-gray-100 text-gray-800', progress: 10 },
  [DocState.IN_PROCESS]: { label: 'En Proceso (0.n)', color: 'bg-blue-100 text-blue-800', progress: 30 },
  [DocState.INTERNAL_REVIEW]: { label: 'Revisión Interna (v0.n)', color: 'bg-yellow-100 text-yellow-800', progress: 60 },
  [DocState.SENT_TO_REFERENT]: { label: 'Enviado a Referente (v1.n)', color: 'bg-purple-100 text-purple-800', progress: 80 },
  [DocState.REFERENT_REVIEW]: { label: 'Revisión Referente (v1.n.i)', color: 'bg-indigo-100 text-indigo-800', progress: 80 },
  [DocState.SENT_TO_CONTROL]: { label: 'Control de Gestión (v1.nAR)', color: 'bg-orange-100 text-orange-800', progress: 90 },
  [DocState.CONTROL_REVIEW]: { label: 'Revisión Control (v1.n.iAR)', color: 'bg-pink-100 text-pink-800', progress: 90 },
  [DocState.APPROVED]: { label: 'Aprobado Final (v1.nACG)', color: 'bg-green-100 text-green-800', progress: 100 },
  [DocState.REJECTED]: { label: 'Rechazado', color: 'bg-red-100 text-red-800', progress: 0 },
};

// Mock Users for Simulation
export const MOCK_USERS = [
  {
    id: 'admin',
    email: 'admin@empresa.com',
    name: 'Administrador General',
    nickname: 'admin',
    role: UserRole.ADMIN,
    avatar: 'https://ui-avatars.com/api/?name=Admin&background=333&color=fff',
    organization: 'Dirección',
    password: 'admin'
  },
  {
    id: 'u-pveloz',
    email: 'pveloz@empresa.com',
    name: 'Patricio Veloz',
    nickname: 'pveloz',
    role: UserRole.COORDINATOR,
    avatar: 'https://ui-avatars.com/api/?name=Patricio+Veloz&background=random',
    organization: 'Coordinación Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-arebolledo',
    email: 'arebolledo@empresa.com',
    name: 'Alejandra Rebolledo',
    nickname: 'arebolledo',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Alejandra+Rebolledo&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-aorellana',
    email: 'Andrea Orellana',
    name: 'Andrea Orellana',
    nickname: 'aorellana',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Andrea+Orellana&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-bsiebold',
    email: 'bsiebold@empresa.com',
    name: 'Barbara Siebold',
    nickname: 'bsiebold',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Barbara+Siebold&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-cvalenzuela',
    email: 'cvalenzuela@empresa.com',
    name: 'Carolina Valenzuela',
    nickname: 'cvalenzuela',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Carolina+Valenzuela&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-caraya',
    email: 'caraya@empresa.com',
    name: 'Christian Araya',
    nickname: 'caraya',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Christian+Araya&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-csalvo',
    email: 'csalvo@empresa.com',
    name: 'Christian Salvo',
    nickname: 'csalvo',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Christian+Salvo&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-jcalquin',
    email: 'jcalquin@empresa.com',
    name: 'Javiera Calquin',
    nickname: 'jcalquin',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Javiera+Calquin&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  },
  {
    id: 'u-mcofre',
    email: 'mcofre@empresa.com',
    name: 'Maximiliano Cofre',
    nickname: 'mcofre',
    role: UserRole.ANALYST,
    avatar: 'https://ui-avatars.com/api/?name=Maximiliano+Cofre&background=random',
    organization: 'Procesos',
    password: 'dgp2026'
  }
];

export const NAME_TO_ID_MAP: Record<string, string> = {
  'Christian Araya': 'u-caraya',
  'Christian Salvo': 'u-csalvo',
  'Carolina Valenzuela': 'u-cvalenzuela',
  'Maximiliano Cofre': 'u-mcofre',
  'Alejandra Rebolledo': 'u-arebolledo',
  'Javiera Calquin': 'u-jcalquin',
  'Andrea Orellana': 'u-aorellana',
  'Barbara Siebold': 'u-bsiebold',
  'Andrea': 'u-aorellana', // Alias for combined
  'Javiera': 'u-jcalquin'  // Alias for combined
};

// Defines the hierarchy and assignments
export const INITIAL_DATA_LOAD = [
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Abastecimiento", "Gestión de Bodegas", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Abastecimiento", "Gestión de Compras", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Abastecimiento", "Gestión de Contratos", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Abastecimiento", "Programación de Fármacos", "Christian Salvo"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Esterilización", "Desinfección de Alto Nivel DAN", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Esterilización", "Esterilización", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Finanzas", "Administración de Activos", "Carolina Valenzuela"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Finanzas", "Gestión de Ingresos y Gastos", "Carolina Valenzuela"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Finanzas", "Gestión de Tesorería", "Carolina Valenzuela"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Finanzas", "Liquidación de Pago", "Carolina Valenzuela"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Finanzas", "Monitoreo y auditoría de cuentas contables", "Carolina Valenzuela"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Finanzas", "Recaudación Ambulatoria", "Christian Salvo"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Asistencia", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Beneficios Funcionarios", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Capacitación Funcionario", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Contratación", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Licencias Médicas", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Reclutamiento y Selección Funcionarios", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Remuneración Funcionarios", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Recursos Humanos", "Trato Laboral", "Maximiliano Cofre"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Servicios Generales", "Gestión de Mesa de Ayuda", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Servicios Generales", "Mantenimiento de Equipos", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Servicios Generales", "Mantenimiento Infraestructura", "Christian Araya"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Servicios Generales", "Roperia", "Alejandra Rebolledo"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Servicios Generales", "Servicios de Vestidores", "Alejandra Rebolledo"],
  ["HPC", "Apoyo Administrativo Logístico e Industrial", "Servicios Generales", "Traslado de Pacientes", "Christian Araya"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Apoyo Atención Ambulatoria", "Admisión Ambulatoria", "Christian Salvo"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Apoyo Atención Ambulatoria", "Admisión Toma de Muestras", "Christian Salvo"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Apoyo Atención Ambulatoria", "Gestión de Agenda", "Javiera Calquin"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Apoyo Atención Ambulatoria", "Gestión de Citas", "Javiera Calquin"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Gestión de la Demanda", "Gestión de IC", "Javiera Calquin"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Gestión de la Demanda", "Listas de Espera GES", "Javiera Calquin"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Gestión de la Demanda", "Listas de Espera No GES", "Javiera Calquin"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "Gestión Prequirúrgico", "Andrea Orellana"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "Quimioterapia", "Andrea Orellana"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "TACO", "Andrea Orellana"],
  ["HPC", "Apoyo Administrativo a la Atención Clínica", "Procedimientos especiales", "Gestión de Fallecidos", "Javiera Calquin"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Anatomía Patológica", "Anatomía Patológica", "Javiera Calquin"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Farmacia", "Farmacia Ambulatoria", "Christian Salvo"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Imagenología", "Imagenología", "Javiera Calquin"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Laboratorio", "Toma de Muestras Ambulatoria", "Barbara Siebold"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Pabellón Quirúrgico", "Gestión de Pabellones", "Andrea Orellana"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Pabellón Quirúrgico", "Procedimientos Endoscópicos", "Andrea Orellana"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Procedimientos", "Atención Procedimientos", "Andrea Orellana"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Procedimientos", "Cirugía Menor Ambulatoria", "Andrea Orellana"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Procedimientos", "Diálisis", "Christian Araya"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Unidad de Medicina Transfusional", "Gestión de Transfusión Sanguínea", "Andrea Orellana"],
  ["HPC", "Apoyo diagnóstico y terapéuticos", "Medicina Física y Rehabilitación", "Kinesiología Ambulatoria", "Carolina Valenzuela"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención Consultas Ambulatorias", "Andrea Orellana"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de Cirugía Maxilofacial", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de Endodoncia", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de Odontopediatría", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de Ortodoncia", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de Periodoncia", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de Radiología Dental", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de Rehabilitación Oral", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Ambulatoria", "Atención de TTM", "Javiera Calquin"],
  ["HPC", "Principales", "Atención Hospitalizados", "Hospital de Día MQ", "Barbara Siebold"],
  ["HPC", "Principales", "Atención Hospitalizados", "Hospital de Día SM", "Barbara Siebold"],
  ["HPC", "Principales", "Atención Hospitalizados", "Hospitalización", "Barbara Siebold"],
  ["HPC", "Principales", "Atención Hospitalizados", "Hospitalización Domiciliaria", "Barbara Siebold"],
  ["HPC", "Principales", "Atención Urgencia", "Atención de Urgencias", "Barbara Siebold"],
  ["HPC", "Dirección", "Control de Gestión", "Elaboración de Reportes", "Carolina Valenzuela"],
  ["HPC", "Dirección", "Control de Gestión", "Programación PCA", "Andrea/Javiera"],
  ["HPC", "Dirección", "Gestión de Proyectos", "Gestión de Proyectos", "Christian Araya"],
  ["HPC", "Dirección", "Relacionamiento con la Comunidad", "Gestión de OIRS", "Alejandra Rebolledo"],
  ["HPC", "Dirección", "Relacionamiento con la Comunidad", "Relaciones Públicas", "Alejandra Rebolledo"],
  ["HSR", "Apoyo Administrativo Logístico e Industrial", "Abastecimiento", "Adquisición de Servicios", "Christian Araya"],
  ["HSR", "Apoyo Administrativo Logístico e Industrial", "Abastecimiento", "Gestión de Compras", "Christian Araya"],
  ["HSR", "Apoyo Administrativo Logístico e Industrial", "Abastecimiento", "Gestión de Contratos", "Christian Araya"],
  ["HSR", "Apoyo Administrativo Logístico e Industrial", "Esterilización", "Esterilización", "Christian Araya"],
  ["HSR", "Apoyo Administrativo Logístico e Industrial", "Finanzas", "Liquidación de Pago", "Carolina Valenzuela"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Apoyo Atención Ambulatoria", "Gestión de Agenda", "Javiera Calquin"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Apoyo Atención Ambulatoria", "Gestión de Citas", "Javiera Calquin"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Gestión de la Demanda", "Gestión de IC", "Javiera Calquin"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Gestión de la Demanda", "Listas de Espera No GES", "Javiera Calquin"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "Gestión Prequirúrgico", "Andrea Orellana"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "Oncología", "Barbara Siebold"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "Oncología Adulto", "Barbara Siebold"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "Oncología Ginecológica", "Barbara Siebold"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Gestión de Pacientes bajo control", "Oncología Infantil", "Barbara Siebold"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Procedimientos especiales", "Gestión de Fallecidos", "Javiera Calquin"],
  ["HSR", "Apoyo Administrativo a la Atención Clínica", "Apoyo Atención Hospitalaria", "Gestión de Camas", "Barbara Siebold"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Anatomía Patológica", "Gestión de Material en Archivo", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Anatomía Patológica", "Procesamiento de Biopsias", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Anatomía Patológica", "Procesamiento de Citología Misceláneas", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Anatomía Patológica", "Procesamiento de Citología PAP", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Farmacia", "Farmacia Ambulatoria", "Christian Salvo"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Imagenología", "Imagenología", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Laboratorio", "Hematología", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Laboratorio", "Recepción de Laboratorio Clínico", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Laboratorio", "Toma de Muestras Ambulatoria", "Barbara Siebold"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Laboratorio", "Uroanálisis", "Javiera Calquin"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Nutrición", "Gestión ANI Adulto en Atención cerrada", "Alejandra Rebolledo"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Nutrición", "Gestión ANI Adulto en Hospitalización Domiciliaria", "Alejandra Rebolledo"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Nutrición", "Gestión de Alimentación y Nutrición", "Alejandra Rebolledo"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Pabellón Quirúrgico", "Gestión de Pabellones", "Andrea Orellana"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Unidad de Medicina Transfusional", "Gestión de Donantes", "Andrea Orellana"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Unidad de Medicina Transfusional", "Gestión de Hemocomponentes", "Andrea Orellana"],
  ["HSR", "Apoyo diagnóstico y terapéuticos", "Unidad de Medicina Transfusional", "Gestión de Transfusión Sanguínea", "Andrea Orellana"],
  ["HSR", "Principales", "Atención Hospitalizados", "Hospital de Día MQ", "Barbara Siebold"],
  ["HSR", "Principales", "Atención Hospitalizados", "Hospitalización", "Barbara Siebold"]
];

// Defines the actual document status, version and type for seed
export const DOCUMENT_STATUS_LOAD = [
  ["1", "HPC", "Gestión de Bodegas", "AS", "v1.0ACG"],
  ["1", "HPC", "Gestión de Bodegas", "FC", "v1.0ACG"],
  ["1", "HPC", "Gestión de Bodegas", "PM", "v1.0"],
  ["2", "HPC", "Gestión de Compras", "AS", "0.2"],
  ["2", "HPC", "Gestión de Compras", "FC", "0.0"],
  ["4", "HPC", "Programación de Fármacos", "AS", "0.1"],
  ["4", "HPC", "Programación de Fármacos", "FC", "0.1"],
  ["5", "HPC", "Desinfección de Alto Nivel DAN", "AS", "v2.1ACG"],
  ["5", "HPC", "Desinfección de Alto Nivel DAN", "FC", "v1.0ACG"],
  ["5", "HPC", "Desinfección de Alto Nivel DAN", "PM", "v1.0ACG"],
  ["5", "HPC", "Desinfección de Alto Nivel DAN", "TO", "v1.0ACG"],
  ["6", "HPC", "Esterilización", "AS", "v1.1ACG"],
  ["6", "HPC", "Esterilización", "FC", "v1.0ACG"],
  ["6", "HPC", "Esterilización", "PM", "v1.0ACG"],
  ["6", "HPC", "Esterilización", "TO", "0.2"],
  ["7", "HPC", "Administración de Activos", "AS", "v1.1ACG"],
  ["7", "HPC", "Administración de Activos", "FC", "v1.0"],
  ["7", "HPC", "Administración de Activos", "PM", "v1.0"],
  ["8", "HPC", "Gestión de Ingresos y Gastos", "AS", "v1.1ACG"],
  ["8", "HPC", "Gestión de Ingresos y Gastos", "FC", "v1.0ACG"],
  ["8", "HPC", "Gestión de Ingresos y Gastos", "PM", "v0.2"],
  ["9", "HPC", "Gestión de Tesorería", "AS", "v0.7"],
  ["9", "HPC", "Gestión de Tesorería", "FC", "0.4"],
  ["10", "HPC", "Liquidación de Pago", "AS", "v1.0"],
  ["10", "HPC", "Liquidación de Pago", "FC", "v0.4"],
  ["11", "HPC", "Monitoreo y auditoría de cuentas contables", "AS", "0.4"],
  ["12", "HPC", "Recaudación Ambulatoria", "AS", "v1.2ACG"],
  ["12", "HPC", "Recaudación Ambulatoria", "FC", "v1.2ACG"],
  ["12", "HPC", "Recaudación Ambulatoria", "PM", "v1.2ACG"],
  ["12", "HPC", "Recaudación Ambulatoria", "TO", "v1.0"],
  ["13", "HPC", "Asistencia", "AS", "v1.0ACG"],
  ["13", "HPC", "Asistencia", "FC", "v1.0ACG"],
  ["13", "HPC", "Asistencia", "PM", "v1.0ACG"],
  ["13", "HPC", "Asistencia", "TO", "v1.0"],
  ["14", "HPC", "Beneficios Funcionarios", "AS", "v1.1ACG"],
  ["14", "HPC", "Beneficios Funcionarios", "FC", "v1.0ACG"],
  ["14", "HPC", "Beneficios Funcionarios", "PM", "v1.0ACG"],
  ["14", "HPC", "Beneficios Funcionarios", "TO", "v1.0"],
  ["15", "HPC", "Capacitación Funcionario", "AS", "v1.1ACG"],
  ["15", "HPC", "Capacitación Funcionario", "FC", "v1.0ACG"],
  ["15", "HPC", "Capacitación Funcionario", "PM", "v1.0ACG"],
  ["15", "HPC", "Capacitación Funcionario", "TO", "v1.0"],
  ["16", "HPC", "Contratación", "AS", "v1.0ACG"],
  ["16", "HPC", "Contratación", "FC", "v1.0ACG"],
  ["16", "HPC", "Contratación", "PM", "v1.0ACG"],
  ["16", "HPC", "Contratación", "TO", "v1.0"],
  ["17", "HPC", "Licencias Médicas", "AS", "v1.0"],
  ["17", "HPC", "Licencias Médicas", "FC", "v1.0"],
  ["17", "HPC", "Licencias Médicas", "PM", "v1.0"],
  ["17", "HPC", "Licencias Médicas", "TO", "0.1"],
  ["18", "HPC", "Reclutamiento y Selección Funcionarios", "AS", "v1.0ACG"],
  ["18", "HPC", "Reclutamiento y Selección Funcionarios", "FC", "v1.0ACG"],
  ["18", "HPC", "Reclutamiento y Selección Funcionarios", "PM", "v1.0ACG"],
  ["18", "HPC", "Reclutamiento y Selección Funcionarios", "TO", "v1.0"],
  ["20", "HPC", "Trato Laboral", "AS", "v1.0ACG"],
  ["20", "HPC", "Trato Laboral", "FC", "v1.0ACG"],
  ["20", "HPC", "Trato Laboral", "PM", "v1.0ACG"],
  ["20", "HPC", "Trato Laboral", "TO", "v1.0"],
  ["21", "HPC", "Gestión de Mesa de Ayuda", "AS", "v1.0ACG"],
  ["21", "HPC", "Gestión de Mesa de Ayuda", "FC", "v1.1ACG"],
  ["21", "HPC", "Gestión de Mesa de Ayuda", "PM", "v1.0ACG"],
  ["22", "HPC", "Mantenimiento de Equipos", "AS", "v2.0ACG"],
  ["22", "HPC", "Mantenimiento de Equipos", "FC", "v1.1ACG"],
  ["22", "HPC", "Mantenimiento de Equipos", "PM", "v1.1ACG"],
  ["22", "HPC", "Mantenimiento de Equipos", "TO", "v1.1ACG"],
  ["23", "HPC", "Mantenimiento Infraestructura", "AS", "v2.0ACG"],
  ["23", "HPC", "Mantenimiento Infraestructura", "FC", "v1.2ACG"],
  ["23", "HPC", "Mantenimiento Infraestructura", "PM", "v1.0ACG"],
  ["23", "HPC", "Mantenimiento Infraestructura", "TO", "v1.0ACG"],
  ["24", "HPC", "Roperia", "FC", "v1.1ACG"],
  ["24", "HPC", "Roperia", "TO", "0.5"],
  ["25", "HPC", "Servicios de Vestidores", "FC", "v1.1ACG"],
  ["26", "HPC", "Traslado de Pacientes", "FC", "v1.0ACG"],
  ["27", "HPC", "Admisión Ambulatoria", "AS", "v1.0ACG"],
  ["27", "HPC", "Admisión Ambulatoria", "FC", "v1.0ACG"],
  ["27", "HPC", "Admisión Ambulatoria", "PM", "v1.3ACG"],
  ["27", "HPC", "Admisión Ambulatoria", "TO", "v1.12"],
  ["28", "HPC", "Admisión Toma de Muestras", "AS", "v1.0ACG"],
  ["28", "HPC", "Admisión Toma de Muestras", "FC", "v1.0ACG"],
  ["28", "HPC", "Admisión Toma de Muestras", "PM", "v1.0AR"],
  ["28", "HPC", "Admisión Toma de Muestras", "TO", "0.0"],
  ["29", "HPC", "Gestión de Agenda", "AS", "v1.0ACG"],
  ["29", "HPC", "Gestión de Agenda", "FC", "v1.0ACG"],
  ["29", "HPC", "Gestión de Agenda", "PM", "v1.0ACG"],
  ["29", "HPC", "Gestión de Agenda", "TO", "0.1"],
  ["30", "HPC", "Gestión de Citas", "AS", "v1.0ACG"],
  ["30", "HPC", "Gestión de Citas", "FC", "v1.0ACG"],
  ["30", "HPC", "Gestión de Citas", "PM", "v1.0ACG"],
  ["30", "HPC", "Gestión de Citas", "TO", "v0.7"],
  ["31", "HPC", "Gestión de IC", "AS", "v1.1ACG"],
  ["31", "HPC", "Gestión de IC", "FC", "v1.0ACG"],
  ["31", "HPC", "Gestión de IC", "PM", "v1.0ACG"],
  ["31", "HPC", "Gestión de IC", "TO", "0.1"],
  ["32", "HPC", "Listas de Espera GES", "AS", "v1.4ACG"],
  ["32", "HPC", "Listas de Espera GES", "FC", "v1.2ACG"],
  ["32", "HPC", "Listas de Espera GES", "PM", "v1.0ACG"],
  ["33", "HPC", "Listas de Espera No GES", "AS", "v1.2ACG"],
  ["33", "HPC", "Listas de Espera No GES", "FC", "v1.0ACG"],
  ["33", "HPC", "Listas de Espera No GES", "PM", "v1.2ACG"],
  ["34", "HPC", "Gestión Prequirúrgico", "FC", "v1.2ACG"],
  ["34", "HPC", "Gestión Prequirúrgico", "TO", "0.1"],
  ["35", "HPC", "Quimioterapia", "FC", "v1.0ACG"],
  ["35", "HPC", "Quimioterapia", "TO", "0.1"],
  ["36", "HPC", "TACO", "AS", "v1.0ACG"],
  ["36", "HPC", "TACO", "FC", "v1.0ACG"],
  ["36", "HPC", "TACO", "PM", "v1.0ACG"],
  ["36", "HPC", "TACO", "TO", "0.2"],
  ["37", "HPC", "Gestión de Fallecidos", "FC", "v1.0ACG"],
  ["37", "HPC", "Gestión de Fallecidos", "TO", "v1.2ACG"],
  ["38", "HPC", "Anatomía Patológica", "AS", "v1.2ACG"],
  ["38", "HPC", "Anatomía Patológica", "FC", "v1.0ACG"],
  ["38", "HPC", "Anatomía Patológica", "PM", "v1.0ACG"],
  ["39", "HPC", "Farmacia Ambulatoria", "AS", "v1.0AR"],
  ["39", "HPC", "Farmacia Ambulatoria", "FC", "v1.0ACG"],
  ["39", "HPC", "Farmacia Ambulatoria", "PM", "v1.2ACG"],
  ["39", "HPC", "Farmacia Ambulatoria", "TO", "v1.0"],
  ["40", "HPC", "Imagenología", "AS", "v1.0ACG"],
  ["40", "HPC", "Imagenología", "FC", "v1.0ACG"],
  ["40", "HPC", "Imagenología", "PM", "v1.0ACG"],
  ["40", "HPC", "Imagenología", "TO", "v1.0ACG"],
  ["41", "HPC", "Toma de Muestras Ambulatoria", "AS", "v1.0ACG"],
  ["41", "HPC", "Toma de Muestras Ambulatoria", "FC", "v1.1ACG"],
  ["41", "HPC", "Toma de Muestras Ambulatoria", "PM", "v1.0ACG"],
  ["41", "HPC", "Toma de Muestras Ambulatoria", "TO", "v0.5"],
  ["42", "HPC", "Gestión de Pabellones", "FC", "v1.0ACG"],
  ["43", "HPC", "Procedimientos Endoscópicos", "AS", "v1.0ACG"],
  ["43", "HPC", "Procedimientos Endoscópicos", "FC", "v1.0ACG"],
  ["43", "HPC", "Procedimientos Endoscópicos", "PM", "v1.0ACG"],
  ["43", "HPC", "Procedimientos Endoscópicos", "TO", "0.0"],
  ["44", "HPC", "Atención Procedimientos", "AS", "v1.0ACG"],
  ["44", "HPC", "Atención Procedimientos", "FC", "v1.0ACG"],
  ["44", "HPC", "Atención Procedimientos", "PM", "v1.0ACG"],
  ["44", "HPC", "Atención Procedimientos", "TO", "v1.0ACG"],
  ["45", "HPC", "Cirugía Menor Ambulatoria", "AS", "v1.0ACG"],
  ["45", "HPC", "Cirugía Menor Ambulatoria", "FC", "v1.0ACG"],
  ["45", "HPC", "Cirugía Menor Ambulatoria", "PM", "v1.0ACG"],
  ["46", "HPC", "Diálisis", "FC", "v1.0ACG"],
  ["46", "HPC", "Diálisis", "TO", "v1.1ACG"],
  ["47", "HPC", "Gestión de Transfusión Sanguínea", "FC", "v1.0ACG"],
  ["47", "HPC", "Gestión de Transfusión Sanguínea", "TO", "0.0"],
  ["48", "HPC", "Kinesiología Ambulatoria", "AS", "0.2"],
  ["49", "HPC", "Atención Consultas Ambulatorias", "AS", "v1.0ACG"],
  ["49", "HPC", "Atención Consultas Ambulatorias", "FC", "v1.0ACG"],
  ["49", "HPC", "Atención Consultas Ambulatorias", "PM", "v1.0ACG"],
  ["49", "HPC", "Atención Consultas Ambulatorias", "TO", "v1.0ACG"],
  ["50", "HPC", "Atención de Cirugía Maxilofacial", "AS", "v1.0ACG"],
  ["50", "HPC", "Atención de Cirugía Maxilofacial", "FC", "v1.0ACG"],
  ["50", "HPC", "Atención de Cirugía Maxilofacial", "PM", "v1.0"],
  ["51", "HPC", "Atención de Endodoncia", "AS", "v1.3ACG"],
  ["51", "HPC", "Atención de Endodoncia", "FC", "v1.0ACG"],
  ["51", "HPC", "Atención de Endodoncia", "PM", "v1.0"],
  ["52", "HPC", "Atención de Odontopediatría", "AS", "v1.0ACG"],
  ["52", "HPC", "Atención de Odontopediatría", "FC", "v1.0ACG"],
  ["52", "HPC", "Atención de Odontopediatría", "PM", "v1.0"],
  ["53", "HPC", "Atención de Ortodoncia", "AS", "v1.1ACG"],
  ["53", "HPC", "Atención de Ortodoncia", "FC", "v1.0ACG"],
  ["53", "HPC", "Atención de Ortodoncia", "PM", "v1.0"],
  ["54", "HPC", "Atención de Periodoncia", "AS", "v1.1ACG"],
  ["54", "HPC", "Atención de Periodoncia", "FC", "v1.0ACG"],
  ["54", "HPC", "Atención de Periodoncia", "PM", "v1.0"],
  ["55", "HPC", "Atención de Radiología Dental", "AS", "v1.0ACG"],
  ["55", "HPC", "Atención de Radiología Dental", "FC", "v1.0ACG"],
  ["55", "HPC", "Atención de Radiología Dental", "PM", "v1.0"],
  ["56", "HPC", "Atención de Rehabilitación Oral", "AS", "v1.2ACG"],
  ["56", "HPC", "Atención de Rehabilitación Oral", "FC", "v1.0ACG"],
  ["56", "HPC", "Atención de Rehabilitación Oral", "PM", "v1.0"],
  ["57", "HPC", "Atención de TTM", "AS", "v1.1ACG"],
  ["57", "HPC", "Atención de TTM", "FC", "v1.0ACG"],
  ["57", "HPC", "Atención de TTM", "PM", "v1.0"],
  ["58", "HPC", "Hospital de Día MQ", "FC", "v1.0ACG"],
  ["59", "HPC", "Hospital de Día SM", "AS", "v1.0ACG"],
  ["59", "HPC", "Hospital de Día SM", "FC", "v1.1ACG"],
  ["59", "HPC", "Hospital de Día SM", "PM", "v1.1ACG"],
  ["59", "HPC", "Hospital de Día SM", "TO", "v0.5"],
  ["60", "HPC", "Hospitalización", "TO", "v0.2"],
  ["61", "HPC", "Hospitalización Domiciliaria", "AS", "v1.0ACG"],
  ["61", "HPC", "Hospitalización Domiciliaria", "FC", "v1.0ACG"],
  ["61", "HPC", "Hospitalización Domiciliaria", "PM", "v1.0ACG"],
  ["61", "HPC", "Hospitalización Domiciliaria", "TO", "v1.0ACG"],
  ["62", "HPC", "Atención de Urgencias", "FC", "v1.0ACG"],
  ["62", "HPC", "Atención de Urgencias", "TO", "v1.0ACG"],
  ["63", "HPC", "Elaboración de Reportes", "AS", "v1.0"],
  ["63", "HPC", "Elaboración de Reportes", "FC", "v0.4"],
  ["63", "HPC", "Elaboración de Reportes", "PM", "0.1"],
  ["64", "HPC", "Programación PCA", "AS", "v1.0ACG"],
  ["64", "HPC", "Programación PCA", "FC", "v1.0ACG"],
  ["64", "HPC", "Programación PCA", "PM", "v1.0ACG"],
  ["64", "HPC", "Programación PCA", "TO", "v1.0ACG"],
  ["65", "HPC", "Gestión de Proyectos", "AS", "v1.0"],
  ["65", "HPC", "Gestión de Proyectos", "FC", "v0.3"],
  ["65", "HPC", "Gestión de Proyectos", "PM", "0.0"],
  ["66", "HPC", "Gestión de OIRS", "AS", "0.4"],
  ["67", "HPC", "Relaciones Públicas", "AS", "v0.5"],
  ["67", "HPC", "Relaciones Públicas", "FC", "v1.0"],
  ["68", "HSR", "Adquisición de Servicios", "AS", "v1.1AR"],
  ["68", "HSR", "Adquisición de Servicios", "FC", "v1.3ACG"],
  ["68", "HSR", "Adquisición de Servicios", "PM", "v1.0ACG"],
  ["69", "HSR", "Gestión de Compras", "AS", "v1.1AR"],
  ["69", "HSR", "Gestión de Compras", "FC", "v1.1AR"],
  ["69", "HSR", "Gestión de Compras", "PM", "v1.0AR"],
  ["69", "HSR", "Gestión de Compras", "TO", "0.0"],
  ["70", "HSR", "Gestión de Contratos", "AS", "0.7"],
  ["70", "HSR", "Gestión de Contratos", "FC", "v1.3AR"],
  ["70", "HSR", "Gestión de Contratos", "PM", "0.0"],
  ["71", "HSR", "Esterilización", "AS", "v1.3.1AR"],
  ["71", "HSR", "Esterilización", "FC", "v1.3AR"],
  ["71", "HSR", "Esterilización", "PM", "v1.1AR"],
  ["71", "HSR", "Esterilización", "TO", "0.2"],
  ["72", "HSR", "Liquidación de Pago", "AS", "0.0"],
  ["72", "HSR", "Liquidación de Pago", "FC", "v0.2"],
  ["73", "HSR", "Gestión de Agenda", "AS", "v1.3AR"],
  ["73", "HSR", "Gestión de Agenda", "FC", "v1.0.3AR"],
  ["73", "HSR", "Gestión de Agenda", "PM", "v1.2AR"],
  ["73", "HSR", "Gestión de Agenda", "TO", "v0.1"],
  ["74", "HSR", "Gestión de Citas", "AS", "v1.1AR"],
  ["74", "HSR", "Gestión de Citas", "FC", "v1.0AR"],
  ["74", "HSR", "Gestión de Citas", "PM", "v1.2AR"],
  ["74", "HSR", "Gestión de Citas", "TO", "0.1"],
  ["75", "HSR", "Gestión de IC", "AS", "v1.2AR"],
  ["75", "HSR", "Gestión de IC", "FC", "v1.2AR"],
  ["75", "HSR", "Gestión de IC", "PM", "v1.0.2AR"],
  ["75", "HSR", "Gestión de IC", "TO", "v0.1"],
  ["76", "HSR", "Listas de Espera No GES", "AS", "v1.3AR"],
  ["76", "HSR", "Listas de Espera No GES", "FC", "v1.1AR"],
  ["76", "HSR", "Listas de Espera No GES", "PM", "v1.2AR"],
  ["77", "HSR", "Gestión Prequirúrgico", "FC", "v1.2AR"],
  ["78", "HSR", "Oncología", "FC", "0.0"],
  ["79", "HSR", "Oncología Adulto", "AS", "v1.2AR"],
  ["79", "HSR", "Oncología Adulto", "PM", "0.0"],
  ["80", "HSR", "Oncología Ginecológica", "AS", "v1.1AR"],
  ["81", "HSR", "Oncología Infantil", "AS", "v0.3"],
  ["82", "HSR", "Gestión de Fallecidos", "AS", "v1.5AR"],
  ["82", "HSR", "Gestión de Fallecidos", "FC", "v1.3AR"],
  ["82", "HSR", "Gestión de Fallecidos", "PM", "v1.1AR"],
  ["82", "HSR", "Gestión de Fallecidos", "TO", "v0.5"],
  ["83", "HSR", "Gestión de Camas", "AS", "0.1"],
  ["83", "HSR", "Gestión de Camas", "FC", "0.0"],
  ["83", "HSR", "Gestión de Camas", "PM", "0.0"],
  ["84", "HSR", "Gestión de Material en Archivo", "FC", "v1.3AR"],
  ["84", "HSR", "Gestión de Material en Archivo", "TO", "0.1"],
  ["85", "HSR", "Procesamiento de Biopsias", "AS", "v1.2.1"],
  ["85", "HSR", "Procesamiento de Biopsias", "FC", "v1.3AR"],
  ["85", "HSR", "Procesamiento de Biopsias", "PM", "v1.1AR"],
  ["86", "HSR", "Procesamiento de Citología Misceláneas", "AS", "v1.1AR"],
  ["86", "HSR", "Procesamiento de Citología Misceláneas", "FC", "v1.3AR"],
  ["86", "HSR", "Procesamiento de Citología Misceláneas", "PM", "v1.1AR"],
  ["86", "HSR", "Procesamiento de Citología Misceláneas", "TO", "v0.1"],
  ["87", "HSR", "Procesamiento de Citología PAP", "AS", "v1.1AR"],
  ["87", "HSR", "Procesamiento de Citología PAP", "FC", "v1.3AR"],
  ["87", "HSR", "Procesamiento de Citología PAP", "PM", "v1.1AR"],
  ["87", "HSR", "Procesamiento de Citología PAP", "TO", "0.0"],
  ["88", "HSR", "Farmacia Ambulatoria", "AS", "v1.1AR"],
  ["88", "HSR", "Farmacia Ambulatoria", "FC", "v1.0AR"],
  ["88", "HSR", "Farmacia Ambulatoria", "PM", "v1.0AR"],
  ["88", "HSR", "Farmacia Ambulatoria", "TO", "v0.6"],
  ["89", "HSR", "Imagenología", "AS", "v0.2"],
  ["89", "HSR", "Imagenología", "FC", "v1.1"],
  ["89", "HSR", "Imagenología", "PM", "0.3"],
  ["90", "HSR", "Hematología", "AS", "0.1"],
  ["90", "HSR", "Hematología", "FC", "0.1"],
  ["91", "HSR", "Recepción de Laboratorio Clínico", "AS", "0.1"],
  ["91", "HSR", "Recepción de Laboratorio Clínico", "FC", "0.1"],
  ["92", "HSR", "Toma de Muestras Ambulatoria", "AS", "v1.0.1AR"],
  ["92", "HSR", "Toma de Muestras Ambulatoria", "FC", "v1.1AR"],
  ["92", "HSR", "Toma de Muestras Ambulatoria", "PM", "v1.1ACG"],
  ["92", "HSR", "Toma de Muestras Ambulatoria", "TO", "0.1"],
  ["93", "HSR", "Uroanálisis", "AS", "0.2"],
  ["93", "HSR", "Uroanálisis", "FC", "0.1"],
  ["96", "HSR", "Gestión de Alimentación y Nutrición", "AS", "0.4"],
  ["96", "HSR", "Gestión de Alimentación y Nutrición", "FC", "v1.0"],
  ["97", "HSR", "Gestión de Pabellones", "FC", "v1.0AR"],
  ["99", "HSR", "Gestión de Hemocomponentes", "AS", "0.2"],
  ["99", "HSR", "Gestión de Hemocomponentes", "FC", "v0.1"],
  ["100", "HSR", "Gestión de Transfusión Sanguínea", "AS", "v1.0"],
  ["100", "HSR", "Gestión de Transfusión Sanguínea", "FC", "v1.0"],
  ["100", "HSR", "Gestión de Transfusión Sanguínea", "PM", "v1.0"],
  ["101", "HSR", "Hospital de Día MQ", "AS", "v1.2AR"],
  ["101", "HSR", "Hospital de Día MQ", "FC", "v1.2.1AR"],
  ["101", "HSR", "Hospital de Día MQ", "PM", "v1.1.1AR"],
  ["101", "HSR", "Hospital de Día MQ", "TO", "v1.0AR"],
  ["102", "HSR", "Hospitalización", "AS", "0.1"]
];

// Definition Matrix for Required Documents per Microprocess
// Format: [Project, Microprocess, AS IS(0/1), FCE(0/1), PM(0/1), TO BE(0/1)]
export const REQUIRED_DOCS_MATRIX = [
    // HPC
    ["HPC", "Admisión Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Admisión Toma de Muestras", 1, 1, 1, 1],
    ["HPC", "Anatomía Patológica", 1, 1, 1, 1],
    ["HPC", "Atención Consultas Ambulatorias", 1, 1, 1, 1],
    ["HPC", "Atención de Urgencias", 0, 1, 0, 1],
    ["HPC", "Atención Procedimientos", 1, 1, 1, 1],
    ["HPC", "Capacitación Funcionario", 1, 1, 1, 1],
    ["HPC", "Cirugía Menor Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Contratación", 1, 1, 1, 1],
    ["HPC", "Desinfección de Alto Nivel DAN", 1, 1, 1, 1],
    ["HPC", "Diálisis", 0, 1, 0, 1],
    ["HPC", "Esterilización", 1, 1, 1, 1],
    ["HPC", "Farmacia Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Gestión de Agenda", 1, 1, 1, 1],
    ["HPC", "Gestión de Citas", 1, 1, 1, 1],
    ["HPC", "Gestión de Contratos", 1, 1, 1, 1],
    ["HPC", "Gestión de Fallecidos", 0, 1, 0, 1],
    ["HPC", "Gestión de IC", 1, 1, 1, 1],
    ["HPC", "Listas de Espera GES", 1, 1, 1, 1],
    ["HPC", "Listas de Espera No GES", 1, 1, 1, 1],
    ["HPC", "Gestión de Pabellones", 0, 1, 0, 1],
    ["HPC", "Gestión Prequirúrgico", 0, 1, 0, 1],
    ["HPC", "Hospital de Día MQ", 0, 1, 0, 1],
    ["HPC", "Hospital de Día SM", 1, 1, 1, 1],
    ["HPC", "Hospitalización Domiciliaria", 1, 1, 1, 1],
    ["HPC", "Imagenología", 1, 1, 1, 1],
    ["HPC", "Laboratorio", 0, 1, 0, 1],
    ["HPC", "Mantenimiento de Equipos", 1, 1, 1, 1],
    ["HPC", "Mantenimiento Infraestructura", 1, 1, 1, 1],
    ["HPC", "Procedimientos Endoscópicos", 1, 1, 1, 1],
    ["HPC", "Programación de Fármacos", 1, 1, 1, 1],
    ["HPC", "Programación PCA", 1, 1, 1, 1],
    ["HPC", "Recaudación Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Reclutamiento y Selección Funcionarios", 1, 1, 1, 1],
    ["HPC", "TACO", 1, 1, 1, 1],
    ["HPC", "Toma de Muestras Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Trato Laboral", 1, 1, 1, 1],
    ["HPC", "Gestión de Transfusión Sanguínea", 0, 1, 0, 1],
    ["HPC", "Asistencia", 1, 1, 1, 1],
    ["HPC", "Atención de Rehabilitación Oral", 1, 1, 1, 1],
    ["HPC", "Atención de Radiología Dental", 1, 1, 1, 1],
    ["HPC", "Atención de Periodoncia", 1, 1, 1, 1],
    ["HPC", "Atención de Odontopediatría", 1, 1, 1, 1],
    ["HPC", "Atención de Endodoncia", 1, 1, 1, 1],
    ["HPC", "Atención de Ortodoncia", 1, 1, 1, 1],
    ["HPC", "Roperia", 0, 1, 0, 1],
    ["HPC", "Atención de Cirugía Maxilofacial", 1, 1, 1, 1],
    ["HPC", "Beneficios Funcionarios", 1, 1, 1, 1],
    ["HPC", "Gestión de Bodegas", 1, 1, 1, 1],
    ["HPC", "Gestión de Compras", 1, 1, 1, 1],
    ["HPC", "Liquidación de Pago", 1, 1, 1, 1],
    ["HPC", "Servicios de Vestidores", 0, 1, 0, 1],
    ["HPC", "Gestión de OIRS", 1, 1, 1, 1],
    ["HPC", "Relaciones Públicas", 1, 1, 1, 1],
    ["HPC", "Gestión de Mesa de Ayuda", 1, 1, 1, 1],
    ["HPC", "Gestión de Proyectos", 1, 1, 1, 1],
    ["HPC", "Administración de Activos", 1, 1, 1, 1],
    ["HPC", "Gestión de Ingresos y Gastos", 1, 1, 1, 1],
    ["HPC", "Gestión de Tesorería", 1, 1, 1, 1],
    ["HPC", "Monitoreo y auditoría de cuentas contables", 1, 1, 1, 1],
    ["HPC", "Elaboración de Reportes", 1, 1, 1, 1],
    ["HPC", "Gestión de Donantes", 0, 1, 0, 1],
    ["HPC", "Atención de TTM", 1, 1, 1, 1],
    ["HPC", "Licencias Médicas", 1, 1, 1, 1],
    ["HPC", "Traslado de Pacientes", 0, 1, 0, 1],
    ["HPC", "Remuneración Funcionarios", 1, 1, 1, 1],
    ["HPC", "Gestión de Hemocomponentes", 0, 1, 0, 1],
    ["HPC", "Kinesiología Ambulatoria", 1, 1, 1, 1],
    ["HPC", "Hospitalización", 0, 1, 0, 1],
    ["HPC", "Quimioterapia", 0, 1, 0, 1],
    
    // HSR
    ["HSR", "Adquisición de Servicios", 0, 0, 0, 1],
    ["HSR", "Esterilización", 0, 0, 0, 1],
    ["HSR", "Farmacia Ambulatoria", 0, 0, 0, 1],
    ["HSR", "Gestión de Agenda", 0, 0, 0, 1],
    ["HSR", "Gestión de Citas", 0, 0, 0, 1],
    ["HSR", "Gestión de Contratos", 0, 0, 0, 1],
    ["HSR", "Gestión de Fallecidos", 0, 0, 0, 1],
    ["HSR", "Gestión de IC", 0, 0, 0, 1],
    ["HSR", "Listas de Espera No GES", 0, 0, 0, 1],
    ["HSR", "Gestión de Pabellones", 0, 0, 0, 1],
    ["HSR", "Gestión Prequirúrgico", 0, 0, 0, 1],
    ["HSR", "Hospital de Día MQ", 0, 0, 0, 1],
    ["HSR", "Imagenología", 0, 0, 0, 1],
    ["HSR", "Laboratorio", 0, 0, 0, 1],
    ["HSR", "Oncología", 0, 0, 0, 1],
    ["HSR", "Toma de Muestras Ambulatoria", 0, 0, 0, 1],
    ["HSR", "Gestión de Transfusión Sanguínea", 0, 0, 0, 1],
    ["HSR", "Procesamiento de Biopsias", 0, 0, 0, 1],
    ["HSR", "Procesamiento de Citología PAP", 0, 0, 0, 1],
    ["HSR", "Oncología Adulto", 0, 0, 0, 1],
    ["HSR", "Oncología Ginecológica", 0, 0, 0, 1],
    ["HSR", "Oncología Infantil", 0, 0, 0, 1],
    ["HSR", "Procesamiento de Citología Misceláneas", 0, 0, 0, 1],
    ["HSR", "Gestión de Bodegas", 0, 0, 0, 1],
    ["HSR", "Gestión de Compras", 0, 0, 0, 1],
    ["HSR", "Liquidación de Pago", 0, 0, 0, 1],
    ["HSR", "Gestión de Donantes", 0, 0, 0, 1],
    ["HSR", "Gestión de Alimentación y Nutrición", 0, 0, 0, 1],
    ["HSR", "Gestión ANI Adulto en Atención cerrada", 0, 0, 0, 1],
    ["HSR", "Gestión ANI Adulto en Atención Ambulatoria", 0, 0, 0, 1],
    ["HSR", "Gestión ANI Adulto en Hospitalización Domiciliaria", 0, 0, 0, 1],
    ["HSR", "Hematología", 0, 0, 0, 1],
    ["HSR", "Uroanálisis", 0, 0, 0, 1],
    ["HSR", "Recepción de Laboratorio Clínico", 0, 0, 0, 1],
    ["HSR", "Gestión de Hemocomponentes", 0, 0, 0, 1],
    ["HSR", "Gestión de Camas", 0, 0, 0, 1],
    ["HSR", "Hospitalización", 0, 0, 0, 1],
    ["HSR", "Gestión de Material en Archivo", 0, 0, 0, 1]
] as [string, string, number, number, number, number][];
